# =========================
# Namespace
# =========================
apiVersion: v1
kind: Namespace
metadata:
  name: ieodp
---
# =========================
# MySQL Secret
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ieodp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==   # root123
  MYSQL_PASSWORD: cGFzczEyMw==        # pass123
---
# =========================
# MySQL StatefulSet
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ieodp
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: ieodpdb
        - name: MYSQL_USER
          value: ieodpuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
---
# =========================
# MySQL Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: ieodp
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
# =========================
# Python Backend Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  namespace: ieodp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python
        image: umatanna9/python-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql-svc
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: ieodpdb
        - name: DB_USER
          value: ieodpuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
# =========================
# Python Backend Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: ieodp
spec:
  selector:
    app: python-backend
  ports:
  - port: 8000
    targetPort: 8000
---
# =========================
# Spring Boot Backend Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
  namespace: ieodp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot
        image: umatanna9/springboot-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-svc:3306/ieodpdb
        - name: SPRING_DATASOURCE_USERNAME
          value: ieodpuser
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        env:
        - name: PYTHON_API_URL
         value: http://python-svc:8000


---
# =========================
# Spring Boot Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: ieodp
spec:
  selector:
    app: springboot-backend
  ports:
  - port: 8080
    targetPort: 8080
---
# =========================
# React Frontend Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: ieodp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
      - name: react
        image: umatanna9/react-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
# =========================
# React Frontend Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: react-svc
  namespace: ieodp
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

